version: "3.7"

services:

    south-driver-controller:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/south-driver-controller:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/netpalm_controller_dockerfile
      environment:
          - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
          - NETPALM_CONFIG=/code/config/config.json
          - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
      ports:
          - "9001:9000"
      networks:
          - docker_netaxe
      depends_on:
          - south-driver-redis
      restart: always

    south-driver-pinned:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/south-driver-pinned:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/netpalm_pinned_worker_dockerfile
      environment:
        - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
        - NETPALM_CONFIG=/code/config/config.json
        - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
      depends_on:
        - south-driver-redis
      networks:
          - docker_netaxe
      restart: always

    south-driver-fifo:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/south-driver-fifo:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/netpalm_fifo_worker_dockerfile
      environment:
        - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
        - NETPALM_CONFIG=/code/config/config.json
        - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
      depends_on:
        - south-driver-redis
      networks:
          - docker_netaxe
      restart: always

    south-driver-redis:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/south-driver-redis:1.0
      build:
        context: .
        dockerfile: ./dockerfiles/netpalm_redis_dockerfile
      ports:
        - "16379:6379"
      networks:
          - docker_netaxe
      restart: always

networks:
  docker_netaxe:
    external: true
